name: maktabatul_kitab
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6 # ✅ Tambahkan di sini dengan spasi yang pas

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
